# Generated by Django 4.1.3 on 2023-08-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoolanderapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='image_url',
            field=models.CharField(default='http://dummyimage.com/115x100.png/cc0000/ffffff', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_full_name',
            field=models.CharField(default='Joe Jonas', max_length=100),
            preserve_default=False,
        ),
    ]
