# Generated by Django 4.1.3 on 2023-08-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoolanderapi', '0002_student_age_student_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='image_url',
            field=models.CharField(default='http://dummyimage.com/115x100.png/cc0000/ffffff', max_length=200),
            preserve_default=False,
        ),
    ]
