# Generated by Django 4.1.3 on 2023-08-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoolanderapi', '0003_assignment_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.CharField(default='title name', max_length=100),
            preserve_default=False,
        ),
    ]
